### PR TITLE
Implement options support. Set xo to auto fix lint errors.

### LINKED ISSUE #72: Allow options as a parameter when creating jobs.
Is there a reason why we don't have options as a parameter at the same level of `interval`, `name`, and `data`?  May I implement this feature?

### PR DESCRIPTION
**Pull request by geosp**
Fixes #72 

- Implement options support.
- Set xo to auto fix lint errors.

Example payload with options:

```js
    let payload = {
      name: sourceID,
      interval: `0 ${_.join(',', frequency)} * * *`,
      data: {
        body: { event, action },
      },
      options: {
        skipImmediate: false,
        timezone: 'America/New_York',
      },
    }
```
- Added unit tests for building URLs with parameters and query.

### CODE REVIEW

**Comment by geosp** [comment]
@OmgImAlexis Would you mind taking a look this PR?

**Comment by 2bigO** [comment]
@geosp LGTM, great work, thanks! Sorry I was away from my computer. Would be cool if you can add a small description to the readme before merge.

**Comment by geosp** [comment]
@keyvan-m-sadeghi No problem. As always thank you. Here are  the changes to the documentation as requested. If is not too much to ask, do think we can have a new version in mpm soon?

**Comment by 2bigO** [comment]
Thanks @geosp 🎉

**Comment by 2bigO** [comment]
Published with `agenda-rest@1.3.0`

**Comment by geosp** [comment]
@keyvan-m-sadeghi Thank you!!

**Pull request merged**
