### PR TITLE
Add Travis badge

### PR DESCRIPTION
**Pull request by simison**
Just testing Travis CI

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
We may need to roll back koa-bodyparser or drop node 6 support.

```
error koa-bodyparser@4.2.0: The engine "node" is incompatible with this module. Expected version ">=7.6".
```

**Comment by simison** [comment]
I'd be inclined to just drop v6 support...

**Comment by simison** [comment]
Adding `test.js`: https://github.com/agenda/agenda-rest/pull/9

**Comment by simison** [comment]
Merging since #9 passes at Travis 👌

**Pull request merged**
