### PR TITLE
Implemented github actions for PRs and publishing to NPM.

### LINKED ISSUE #95: There is a mismatch between the npm package version and the sour code package.json.
Looking at https://github.com/agenda/agenda-rest/blob/master/package.json#L3 it indicates version `1.2.4` but NPM has 1.3.0.
I propose we change the version to `1.3.1`.

### LINKED ISSUE #97: Implement GitHub actions.
Implement GitHub actions for PRs and for NPM deployment.

### PR DESCRIPTION
**Pull request by geosp**
Fixes #97 
Fixes #95

- [x] Fixed version number.
- [x] Implemented action for pull request creation.
- [x] Implemented action for NPM deployment when PR is merged into the master branch.
- [ ] I need administrative rights or someone with admin rights needs to create the NPM security token.

### CODE REVIEW

**Comment by 2bigO** [comment]
@geosp are you sure you need admin access for the NPM security token? Because I don't have admin access, not sure if @OmgImAlexis has either, and I don't see any options other than READ and READ/WRITE in npm team's setting.

Try creating a token with your own npm account, I suspect you're not able to publish because you still don't have 2FA enabled.

https://docs.npmjs.com/configuring-two-factor-authentication

**Review by 2bigO — APPROVED** [review]
The rest LGTM

**Comment by geosp** [comment]
@keyvan-m-sadeghi, and @OmgImAlexis we need to create the security token in NPM and then add it to GitHub so that the actions have access to it. I don't have access to the `Settings` for this project therefore I'm unable to add the security token under the settings as a secret. I'm referencing the security token right here [NPM Publish Action](https://github.com/agenda/agenda-rest/pull/96/files#diff-356d6971e4dd6fa5d46bdd3613151842c17f86eb55c363e13f44c31a95d1ea00R22). [Here](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) are the instructions on how to add the token to GitHub. The secret name should be `npm_token`.

**Comment by geosp** [comment]
I think @OmgImAlexis original idea was to secure publishing of the the application to NPM by referecing an NPM security token within GitHub and asuring that only the repository Administrator/Administrators have access to the token.

**Comment by geosp** [comment]
If you guys are interested [this is the library](https://github.com/nektos/act) I'm using to test the actions in my local environment. The command to run the pull_request action is:

```sh
act pull_request
```

agenda_rest_act

**Comment by geosp** [comment]
[Here](https://github.com/marketplace?type=actions) is a list of action types.

**Pull request merged**
